# ========================================
# ROOT ORCHESTRATOR - Include only
# ========================================

include:
  - path: ./core/compose.yml

  # <<GTK_INCLUDES>>
  - path: ./gtk-companies/gtk-acme/docker-compose.yml