version: '3.9'

services:

  api:
    build: .
    container_name: maintenance-api
    restart: unless-stopped

    ports:
      - "8000:8000"

    env_file:
      - .env

    volumes:
      - ./uploads:/uploads

    depends_on:
      - postgres

  postgres:
    image: postgres:16

    container_name: postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: maintenance
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: