"""Guards for the Alembic `target_metadata` and the tables it deliberately omits.

The regression these prevent is the most destructive one in this repository's
history. `alembic/env.py` imported only `fsm_user` and `token_blacklist`, so
`target_metadata` described a two-table database. Autogenerate compares
`target_metadata` against the database it is connected to and emits the
difference: measured against a database built from `deploy/schema.sql`, the old
two-table metadata made it emit `remove_table` for 20 of the 23 live tables.
`alembic upgrade head` would then have deleted most of the database on a server
shared with other applications.

The omission was invisible because `tests/conftest.py` builds the test schema
with `Base.metadata.create_all`, so the suite agrees with the models by
construction and can never detect the models disagreeing with the database.

Five tables are in the database and deliberately have no models, because their
features are unbuilt. They are kept for future features (TICKET-018), so
autogenerate must be told to skip them: a table with no model looks exactly like a
table nobody wants any more. That exclusion is the whole reason this file exists.

No database is required, so these run in CI.
"""
import importlib
import pkgutil
import re
from pathlib import Path

import app.models
from app.models.base import Base

REPO_ROOT = Path(__file__).resolve().parents[1]
ENV_PY = REPO_ROOT / "alembic" / "env.py"
SCHEMA_SQL = REPO_ROOT / "deploy" / "schema.sql"

# Alembic's own bookkeeping table. It is in the dump because pg_dump emitted it,
# and it is in the live database, but it is not a table this project models.
ALEMBIC_OWN_TABLES = ("alembic_version",)


def _import_every_model() -> None:
    """Import every module in app.models, which is what env.py must do."""
    for module in pkgutil.iter_modules(app.models.__path__):
        importlib.import_module(f"app.models.{module.name}")


def _env_py_text() -> str:
    assert ENV_PY.exists(), "alembic/env.py is missing, so migrations cannot run at all."
    return ENV_PY.read_text(encoding="utf-8")


def _model_module_names() -> list[str]:
    return sorted(
        module.name
        for module in pkgutil.iter_modules(app.models.__path__)
        if not module.name.startswith("_")
    )


def _dump_tables() -> set[str]:
    text = SCHEMA_SQL.read_text(encoding="utf-8")
    return set(re.findall(r"^CREATE TABLE (?:public\.)?(\w+)", text, re.MULTILINE))


# ---------------------------------------------------------------------------
# target_metadata must describe the whole application
# ---------------------------------------------------------------------------


def test_env_py_imports_every_model_module() -> None:
    """A model module that env.py forgets is a table autogenerate will drop.

    This is the guard for the 20-table deletion risk. It is a static check on the
    import list rather than a behavioural one, because proving the consequence
    needs a live database and this must run in CI.
    """
    text = _env_py_text()
    imported = set(re.findall(r"^import app\.models\.(\w+)", text, re.MULTILINE))
    imported |= set(re.findall(r"^from app\.models\.(\w+) import", text, re.MULTILINE))

    missing = [name for name in _model_module_names() if name not in imported]
    assert not missing, (
        f"alembic/env.py does not import {missing}. Any model module missing from "
        f"env.py leaves its table out of target_metadata, and autogenerate emits "
        f"drop_table for every table it does not see in the models. See TICKET-019."
    )


def test_target_metadata_covers_every_model_table() -> None:
    """The 17 model tables must all be in Base.metadata once every model is imported."""
    _import_every_model()
    model_tables = set(Base.metadata.tables)

    assert len(model_tables) == 17, (
        f"expected 17 model tables, found {len(model_tables)}. The count is pinned "
        f"because a silently dropped model is indistinguishable from an intended "
        f"removal. Found: {sorted(model_tables)}"
    )


# ---------------------------------------------------------------------------
# the five tables that have no models, on purpose
# ---------------------------------------------------------------------------


def test_reserved_tables_are_exactly_the_unmodelled_tables_in_the_schema() -> None:
    """The exclusion list must match reality, or it guards nothing.

    Tying the constant to the dump means adding or removing a table without a
    model fails here, instead of quietly turning into a `drop_table` in someone's
    autogenerated revision.

    The list is read from the application module rather than restated here. An
    earlier draft of this file declared its own copy, and the two drifted on a
    single character: the table is spelled `hollidays` in the live database, and
    the duplicate said `holidays`. Restating a constant is how a guard starts
    asserting something that is no longer true.
    """
    from app.models.reserved import RESERVED_TABLES_WITHOUT_MODELS

    _import_every_model()
    unmodelled = _dump_tables() - set(Base.metadata.tables) - set(ALEMBIC_OWN_TABLES)

    assert sorted(unmodelled) == sorted(RESERVED_TABLES_WITHOUT_MODELS), (
        f"the tables in deploy/schema.sql that no model describes are {sorted(unmodelled)}, "
        f"but the exclusion list is {sorted(RESERVED_TABLES_WITHOUT_MODELS)}. They must be "
        f"the same set. These tables are kept for unbuilt features (TICKET-018), so a table "
        f"missing from the list is a table autogenerate will propose to drop."
    )


class _FakeElement:
    """One column reference inside a foreign key."""

    def __init__(self, target_fullname: str) -> None:
        self.target_fullname = target_fullname


class _FakeForeignKey:
    """The shape `include_object` receives for a reflected foreign key.

    Alembic hands the hook the `ForeignKeyConstraint` itself, so a stub built to
    the same contract tests the filter without needing a database. `include_object`
    is documented against that contract, and `alembic check` against a real
    database is the check that the contract held.
    """

    def __init__(self, *target_fullnames: str) -> None:
        self.elements = [_FakeElement(target) for target in target_fullnames]


def _fake_fk(referenced: tuple[str, str]) -> _FakeForeignKey:
    """Build a foreign key referencing `referenced`, e.g. `("uom", "unit")`."""
    return _FakeForeignKey(".".join(referenced))


def test_include_object_hook_skips_the_reserved_tables_only() -> None:
    from app.models.reserved import RESERVED_TABLES_WITHOUT_MODELS, include_object

    for name in RESERVED_TABLES_WITHOUT_MODELS:
        obj, type_ = object(), "table"
        assert include_object(obj, name, type_, True, None) is False, (
            f"{name!r} has no model and is kept for a future feature, so autogenerate "
            f"must skip it. See TICKET-018."
        )

    for name in ("tickets", "photos", "token_blacklist"):
        obj, type_ = object(), "table"
        assert include_object(obj, name, type_, True, None) is True, (
            f"{name!r} is modelled and must stay in autogenerate's scope. The hook "
            f"over-filters if it excludes it."
        )


def test_include_object_hook_skips_foreign_keys_into_reserved_tables() -> None:
    """`spares.unit` really does reference `uom`, and the model cannot say so.

    `uom` is reserved and unmodelled, so `Spare.unit` carries no
    `ForeignKey("uom.unit")`: an unresolvable reference breaks
    `Base.metadata.create_all`, which is how the test suite builds its schema.
    Live has the constraint anyway, so without a second exclusion autogenerate
    reports it as surplus and `alembic upgrade head` drops referential integrity
    that the database deliberately has.
    """
    from app.models.reserved import include_object

    assert include_object(_fake_fk(("uom", "unit")), "spares_unit_fkey",
                          "foreign_key_constraint", True, None) is False

    for referenced in ("markets", "equipments", "fsm_users", "tickets"):
        assert include_object(_fake_fk((referenced, "id")), f"x_{referenced}_fkey",
                              "foreign_key_constraint", True, None) is True, (
            f"a foreign key to the modelled table {referenced!r} must stay in scope"
        )


def test_include_object_hook_matches_a_schema_qualified_reference() -> None:
    """`public.uom.unit` must resolve to the same table as `uom.unit`.

    Reflected names are schema-qualified when the reference is written that
    way, so matching on the first dotted component would resolve the reference to
    a table called `public`, find no such reserved table, and let the
    constraint through.
    """
    from app.models.reserved import include_object

    assert include_object(_fake_fk(("public.uom", "unit")), "spares_unit_fkey",
                          "foreign_key_constraint", True, None) is False


def test_include_object_hook_ignores_the_foreign_key_own_name() -> None:
    """The filter keys on the referenced table, never on the constraint name.

    Without this, a constraint that merely happens to be *named* after a reserved
    table would be filtered, which is the over-filtering the column and index
    cases already guard against.
    """
    from app.models.reserved import include_object

    assert include_object(_fake_fk(("markets", "market_id")), "holidays_fkey",
                          "foreign_key_constraint", True, None) is True


def test_include_object_hook_tolerates_a_constraint_without_elements() -> None:
    """A malformed or unexpected object must not raise out of the hook.

    `include_object` runs inside autogenerate for every object of every type.
    Raising here would abort the whole comparison rather than skip one
    constraint, so anything without usable elements is simply kept in scope.
    """
    from app.models.reserved import include_object

    assert include_object(object(), "some_fkey", "foreign_key_constraint",
                          True, None) is True

    class NoTargetFullname:
        elements = ()

    assert include_object(NoTargetFullname(), "x_fkey", "foreign_key_constraint",
                          True, None) is True


def test_include_object_hook_only_filters_tables_and_foreign_keys() -> None:
    """A column or index named like a reserved table must not be filtered."""
    from app.models.reserved import include_object

    assert include_object(object(), "holidays", "column", True, None) is True
    assert include_object(object(), "materials", "index", True, None) is True
    assert include_object(object(), "spares", "table", True, None) is True


def test_env_py_wires_the_hook_into_both_configure_calls() -> None:
    """include_object must be passed in the offline and the online path.

    Passing it only in `run_migrations_online` would leave `alembic upgrade
    --sql` and offline autogenerate unprotected, which is how a guard ends up
    looking effective while a real code path skips it.
    """
    text = _env_py_text()
    configure_calls = re.findall(r"context\.configure\((.*?)\n\s*\)", text, re.DOTALL)
    assert len(configure_calls) == 2, (
        f"expected two context.configure calls (offline and online), found "
        f"{len(configure_calls)}. If the structure changed, re-check that both paths "
        f"are protected."
    )
    for index, call in enumerate(configure_calls):
        assert "include_object" in call, (
            f"context.configure call {index} does not pass include_object, so that "
            f"path will propose drop_table for the tables kept for unbuilt features."
        )
