"""Align photos.maintenance_id FK type (Integer → Uuid)

Revision ID: 0004_align_photos_maintenance_id_fk
Revises: 0003_resume_maintenance
Create Date: 2026-09-03
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0004_align_photos_maintenance_id_fk"
down_revision: Union[str, None] = "0003_resume_maintenance"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# The FK on photos.maintenance_id is auto-generated by SQLAlchemy/Postgres with
# the default naming convention `<table>_<column>_fkey` unless it was created
# with an explicit name. Query it once so the migration works regardless of the
# actual constraint name (only one FK points at maintenances from photos).
_FK_LOOKUP_SQL = """
    SELECT conname FROM pg_constraint
    WHERE conrelid = 'photos'::regclass
      AND contype = 'f'
      AND confrelid = 'maintenances'::regclass
    LIMIT 1
"""


def _get_photos_fk_name() -> str:
    conn = op.get_bind()
    row = conn.execute(sa.text(_FK_LOOKUP_SQL)).first()
    if row is None:
        raise RuntimeError("Expected an FK from photos.maintenance_id to maintenances.maintenance_id")
    return row[0]


def upgrade() -> None:
    fk_name = _get_photos_fk_name()

    # Drop existing FK constraint so the column type can change
    op.drop_constraint(fk_name, "photos", type_="foreignkey")

    # Alter column from Integer to Uuid
    op.alter_column(
        "photos",
        "maintenance_id",
        type_=sa.Uuid(),
        postgresql_using="maintenance_id::uuid",
    )

    # Re-add FK constraint with the canonical name
    op.create_foreign_key(
        "photos_maintenance_id_fkey",
        "photos",
        "maintenances",
        ["maintenance_id"],
        ["maintenance_id"],
    )


def downgrade() -> None:
    op.drop_constraint("photos_maintenance_id_fkey", "photos", type_="foreignkey")

    # Revert column type to Integer
    op.alter_column(
        "photos",
        "maintenance_id",
        type_=sa.Integer(),
        postgresql_using="maintenance_id::integer",
    )

    op.create_foreign_key(
        "photos_maintenance_id_fkey",
        "photos",
        "maintenances",
        ["maintenance_id"],
        ["maintenance_id"],
    )
