# TYPE  DATABASE  USER  ADDRESS                    METHOD
# --- Red interna Docker ---
local   all       all                              trust
host    all       all   172.16.0.0/12              scram-sha-256
host    all       all   172.23.0.0/16              scram-sha-256
host    all       all   172.28.0.0/16              scram-sha-256      # BEFORE: trust
host    all       all   10.0.0.0/8                 scram-sha-256

# --- AppSheet IPs (manejadas por iptables, aquí permisivas) ---
host    all       all   0.0.0.0/0                  scram-sha-256
host    all       all   ::/0                       scram-sha-256

# --- BigQuery IPs (manejadas por iptables, aquí permisivas) PENDIENTE ---


# --- Replicación ---
local   replication all                            trust
host    replication all  127.0.0.1/32              trust